#!/bin/bash
#
# Title:      Reference Title File - PGBlitz
# Author(s):  Admin9705 & https://github.com/PGBlitz/PGClone/graphs/contributors - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  vars:
    service_vars:
      - {name: crypt.service}
      - {name: gd.service}
      - {name: gc.service}
      - {name: sd.service}
      - {name: sc.service}
      - {name: pgunity.service}
      - {name: transfer.service}
  tasks:
    - name: Stop All Docker Containers
      shell: docker stop $(docker ps -a -q)
      ignore_errors: yes

    - name: Checking Existing Service Name
      stat:
        path: "/etc/systemd/system/{{ item.name }}"
      with_items: "{{ service_vars }}"
      register: check_service_name

    - name: Stop If Service Is Running
      systemd: state=stopped name={{ item.item.name }} daemon_reload=yes enabled=no
      with_items: "{{ check_service_name.results }}"
      when: item.stat.exists

    - name: Remove Services
      file:
        path: "/etc/systemd/system/{{ item.item.name }}"
        state: absent
      with_items: "{{ check_service_name.results }}"
      when: item.stat.exists
